mdmorris_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
#from django.contrib.sitemaps.views import index
from django.contrib.sitemaps.views import sitemap
from django.views.defaults import bad_request, page_not_found, permission_denied, server_error


from django.views.generic.base import RedirectView
from django_xmlrpc.views import handle_xmlrpc
from frontpage import views as frontpage_views

from zinnia.sitemaps import AuthorSitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import TagSitemap
from photologue.sitemaps import GallerySitemap, PhotoSitemap
from django.views.generic import TemplateView

import photologue_custom

urlpatterns = [
   url(r'^home/$', frontpage_views.home_view, name='home'),
   url(r'^about-me/$', frontpage_views.aboutme_view, name='about_me'),
#   url(r'^how-to-order', RedirectView.as_view(url='home', permanent=True), name='commission'),
   url(r'^contact-mark/$', frontpage_views.contactme_view, name='contact-me'),
   url(r'^links/(?P<slug>[\-\d\w]+)/$', frontpage_views.links_view, name='links'),
#   url(r'^buy-a-necklace', RedirectView.as_view(url='home', permanent=True), name='buy-a-necklace'),
#  url(r'^view-cart', RedirectView.as_view(url='home', permanent=True), name='view-cart'),
#  url(r'^blog', RedirectView.as_view(url='photologue/', permanent=True), name='blog'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^weblog/sitemap/', RedirectView.as_view(url='/sitemap.xml', permanent=True), name='sitemap'),
    url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^xmlrpc/$', handle_xmlrpc),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^projects/', include('photologue_custom.urls', namespace='photologue-custom')),
    url(r'^explore/', include('photologue.urls', namespace='photologue')),
    url(r'^$', RedirectView.as_view(url='home', permanent=True))
] 


sitemaps = {
	'tags': TagSitemap,
	'blog':EntrySitemap,
	'authors': AuthorSitemap,
	'categories': CategorySitemap,
	'photologue_galleries': GallerySitemap,
	'photologue_photos': PhotoSitemap,
}

urlpatterns += [
#************************
# This doesn't work so replaced using sitemap instead of index, worked!
#	url(r'^sitemap.xml$',
#		index,
#		{'sitemaps': sitemaps}),
#******************************
	url(r'^sitemap.xml$',
		sitemap,
		{'sitemaps': sitemaps}),
	
	url(r'^sitemap-(?P<section>.+)\.xml$',
		sitemap,
		{'sitemaps': sitemaps}, name='sitemaps'),
	]

urlpatterns += [
	url(r'^400/$', bad_request),
	url(r'^403/$', permission_denied),
	url(r'^404/$', page_not_found),
	url(r'^500/$', server_error),
]

#Add Bing Verify Ownership Authentication and Google verification too
urlpatterns += [
	url(r'^BingSiteAuth\.xml', TemplateView.as_view(template_name='zinnia/BingSiteAuth.xml', content_type='text/xml')),
	url(r'^googled9943244a1802ac7\.html', TemplateView.as_view(template_name='zinnia/googled9943244a1802ac7.html', content_type='text/html')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		document_root=settings.MEDIA_ROOT)

my_zinnia_bootstrap/templates/zinnia/_entry_detail.html
{% extends "zinnia/_entry_detail_base.html" %}

{% block entry-discussions %}{% endblock entry-discussions %}

my_zinnia_bootstrap/templates/zinnia/_entry_detail_base.html
{% load comments i18n zinnia %}
{% load disqus_tags %}
<article id="entry-{{ object.pk }}" class="hentry{% if object.featured %} featured{% endif %}">
  {% block entry-header %}
  <header class="entry-header page-header">
    <h2 class="entry-title">
    {% block entry-title %}
      <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">
        {{ object.title|widont }}
      </a>
    {% endblock entry-title %}
    {% block entry-info %}
      <br />
      <small class="entry-info">
        {% block entry-authors %}
        {% with authors=object.authors.all %}
        {% if authors|length %}
        {% trans "Written by" %}
        {% for author in authors %}
        <span class="vcard author">
          <a href="{{ author.get_absolute_url }}" class="fn url{% if not author.get_full_name %} nickname{% endif %}" rel="author"
             title="{% blocktrans %}Show all {{ author }}'s entries{% endblocktrans %}">{{ author }}</a></span>{% if not forloop.last %}, {% endif %}
        {% endfor %}
        {% trans "on" context "on date" %}
        {% else %}
        {% trans "Written on" %}
        {% endif %}
        {% endwith %}
        {% endblock entry-authors %}
        {% block entry-published %}
        <time class="published" datetime="{{ object.publication_date|date:"c" }}" pubdate="pubdate">{{ object.publication_date|date:"DATE_FORMAT" }}</time>
        {% endblock entry-published %}
        {% block entry-categories %}
        {% with categories=object.categories.all %}
        {% if categories|length %}
        {% trans "in" %}
        {% for category in categories %}
        <a href="{{ category.get_absolute_url }}"
           title="{% blocktrans %}Show all entries in {{ category }}{% endblocktrans %}"
           rel="tag category">{{ category }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}.
        {% endwith %}
        {% endblock entry-categories %}
      </small>
    {% endblock entry-info %}
    </h2>
    {% block entry-last-update %}
    <p class="entry-last-update" style="display: none;">
      {% trans "Last update on" %} <time class="updated" datetime="{{ object.last_update|date:"c" }}">{{ object.last_update|date:"DATE_FORMAT" }}</time>.
    </p>
    {% endblock entry-last-update %}
  </header>
  {% endblock entry-header %}

  {% block entry-body %}
  <div class="entry-body">
    {% block entry-image %}
    {% if object.image %}
    <div class="entry-image">
      <p>
        {% if continue_reading %}
        <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">
          {% endif %}
          <img src="{{ object.image.url }}" alt="{{ object.title }}" class="img-thumbnail img-responsive" />
          {% if continue_reading %}
        </a>
        {% endif %}
      </p>
    </div>
    {% endif %}
    {% endblock entry-image %}
    {% block entry-content %}
    <div class="entry-content lead">
      {{ object_content|safe }}
    </div>
    {% endblock entry-content %}
    {% block continue-reading %}
    {% if continue_reading and object_content.has_more %}
    <p class="continue-reading">
      <a href="{{ object.get_absolute_url }}"
         title="{% blocktrans with object=object.title percent=object_content.remaining_percent|floatformat:0 %}{{ percent }}% of {{ object }} still remains to read.{% endblocktrans %}"
         rel="bookmark" class="btn btn-primary">
        {% trans "Continue reading" %}
      </a>
    </p>
    {% endif %}
    {% endblock continue-reading %}
  </div>
  {% endblock entry-body %}

  {% block entry-footer %}
  <footer class="entry-footer well">
    {% block entry-tags %}
    <p class="entry-tags">
      <span class="glyphicon glyphicon-tags"></span> <strong>{% trans "Tags" %}</strong> :
      {% for tag in object.tags_list %}
      <a href="{% url 'zinnia:tag_detail' tag %}"
         title="{% blocktrans %}Show all entries tagged by {{ tag }}{% endblocktrans %}"
         rel="tag">{{ tag }}</a>
      {% empty %}
      <span>{% trans "No tags" %}</span>
      {% endfor %}
    </p>
    {% endblock entry-tags %}
    {% block entry-shorturl %}
    <p class="entry-shorturl">
      <span class="glyphicon glyphicon-bookmark"></span> <strong>{% trans "Short url" %}</strong> :
      <a href="{{ object.short_url }}"
         title="{% blocktrans with object=object.title %}Short URL to {{ object }}{% endblocktrans %}"
         rel="shortlink">
        {{ object.short_url }}
      </a>
    </p>
    {% endblock entry-shorturl %}



<!--    {% disqus_show_comments %} -->



    {% block entry-discussions %}
    <p class="entry-discussions">
      <span class="glyphicon glyphicon-comment"></span> <strong>{% trans "Discussions" %}</strong> :
      {% block entry-comments %}
      {% with comment_count=object.comment_count %}
      {% if comment_count %}
      <a href="{{ object.get_absolute_url }}#comments"
         title="{% blocktrans with object=object.title %}Comments on {{ object }}{% endblocktrans %}">
        {% blocktrans count comment_count=comment_count %}{{ comment_count }} comment{% plural %}{{ comment_count }} comments{% endblocktrans %}
      </a>
      {% else %}
      {% if object.comments_are_open %}
      {% trans "No comments yet." %}
      <a href="{{ object.get_absolute_url }}#comment-form"
         title="{% blocktrans with object=object.title %}Leave a comment on {{ object }}{% endblocktrans %}">
        {% trans "Be first to comment!" %}
      </a>
      {% else %}
      {% trans "Comments are closed." %}
      {% endif %}
      {% endif %}
      {% endwith %}
      {% endblock entry-comments %}
      {% block entry-pingbacks %}
      {% with pingback_count=object.pingback_count %}
      {% if pingback_count %}
      , <a href="{{ object.get_absolute_url }}#pingbacks" title="{% blocktrans with object=object.title %}Pingbacks on {{ object }}{% endblocktrans %}">
        {% blocktrans count pingback_count=pingback_count %}{{ pingback_count }} pingback{% plural %}{{ pingback_count }} pingbacks{% endblocktrans %}
      </a>
      {% endif %}
      {% endwith %}
      {% endblock entry-pingbacks %}
      {% block entry-trackbacks %}
      {% with trackback_count=object.trackback_count %}
      {% if trackback_count %}
      , <a href="{{ object.get_absolute_url }}#trackbacks" title="{% blocktrans with object=object.title %}Trackbacks on {{ object }}{% endblocktrans %}">
        {% blocktrans count trackback_count=trackback_count %}{{ trackback_count }} trackback{% plural %}{{ trackback_count }} trackbacks{% endblocktrans %}
      </a>
      {% endif %}
      {% endwith %}
      {% endblock entry-trackbacks %}
    </p>
    {% endblock entry-discussions %}
  </footer>
  {% endblock entry-footer %}
</article>

my_zinnia_bootstrap/templates/zinnia/author_list.html
{% extends "zinnia:zinnia/author_list.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Author list" %}</h1>

<ul class="list-group">
  {% for object in object_list %}
  <li class="vcard list-group-item">
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}"
       class="fn url{% if not author.get_full_name %} nickname{% endif %}">{{ object }}</a>
    <span class="badge">
      {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    </span>
  </li>
  {% empty %}
  <li>
    {% trans "No authors yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

my_zinnia_bootstrap/templates/zinnia/base.html
{% extends "zinnia:zinnia/base.html" %}
{% load zinnia i18n %}
{% load static %}

{% block sidebar %}
{% block welcome_class %}
<aside id="widget-welcome" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Welcome to my Weblog" %}
  </div>
  <div class="panel-body">
    <img src='{% static "zinnia_bootstrap/img/profile_pic.jpg" %}' class="img-thumbnail" alt="Mark Morris" width="150" height="236">
     <p>
      {% trans "Here you will find all the things that I've been up to, both recently and in the past." %}
    </p>
    <p>
      {% trans "Please feel free to make any comments." %}
    </p>
    <p>
      {% trans "Thanks for dropping by!" %}
    </p>
  </div>
</aside>
{% endblock welcome_class %}

<aside id="widget-categories" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Categories" %}
  </div>
  {% get_categories %}
</aside>
<aside id="widget-authors" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Authors" %}
  </div>
  {% get_authors %}
</aside>
<aside id="widget-recents" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Recent entries" %}
  </div>
  {% get_recent_entries %}
</aside>
<aside id="widget-comments" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Recent comments" %}
  </div>
  {% load disqus_tags %}
  {% disqus_recent_comments shortname 2 50 0 24 %}
</aside> 
<aside id="widget-linkbacks" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Recent linkbacks" %}
  </div>
  {% get_recent_linkbacks %}
</aside>
<aside id="widget-randoms" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Random entries" %}
  </div>
  {% get_random_entries %}
</aside>
<aside id="widget-populars" class="widget panel panel-default">
  <div class="panel-heading">
    {% trans "Popular entries" %}
  </div>
  {% get_popular_entries %}
</aside>
{% if user.is_authenticated %}
<aside id="widget-tools" class="widget panel panel-danger">
  <div class="panel-heading">
    {% trans "Tools" %}
  </div>
  <ul class="list-group">
    {% if perms.zinnia %}
    <li class="list-group-item">
      <a href="{% url 'admin:app_list' 'zinnia' %}" title="{% trans "Dashboard" %}">
        <span class="glyphicon glyphicon-book"></span>
        {% trans "Dashboard" %}
      </a>
    </li>
    {% endif %}
    {% if perms.zinnia.add_entry %}
    <li class="list-group-item">
      <a href="{% url 'admin:zinnia_entry_add' %}" title="{% trans "Post an entry" %}">
        <span class="glyphicon glyphicon-pencil"></span>
        {% trans "Post an entry" %}
      </a>
    </li>
    {% endif %}
    {% block admin-tools %}
    {% endblock admin-tools %}
    <li class="list-group-item">
      <a href="{% url 'admin:logout' %}" title="{% trans "Log out" %}">
        <span class="glyphicon glyphicon-off"></span>
        {% trans "Log out" %}
      </a>
    </li>
  </ul>
</aside>
{% endif %}
{% endblock sidebar %}

my_zinnia_bootstrap/templates/zinnia/entry_detail.html
{% extends "zinnia/entry_detail_base.html" %}
{% load disqus_tags %}

{% block welcome_class %}{% endblock welcome_class %}
{% block entry-comments %}
{% disqus_show_comments %}
{% endblock entry-comments %}

my_zinnia_bootstrap/templates/zinnia/entry_search.html
{% extends "zinnia:zinnia/entry_search.html" %}
{% load i18n zinnia %}

{% block content-title %}
<h1>{% blocktrans %}Search results for '{{ pattern }}'{% endblocktrans %}</h1>

{% if error %}
<p class="alert alert-error">{{ error }}</p>
{% else %}
<p class="feed">
  <span class="glyphicon glyphicon-list-alt"></span>
  <a href="{% url 'zinnia:entry_search_feed' %}?pattern={{ pattern }}" title="{% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}">
    {% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}
  </a>
</p>
{% endif %}

{% if object_list %}
<p class="alert alert-success">
  {% blocktrans count entry_count=paginator.count %}{{ entry_count }} entry found{% plural %}{{ entry_count }} entries found{% endblocktrans %}
</p>
{% endif %}

{% endblock content-title %}

{% block content-loop %}
{% if not error %}
{% for object in object_list %}
  {% zinnia_loop_template object.content_template as template %}
  {% include template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
<p class="alert alert-info">{% trans "Nothing found." %}</p>
{% endfor %}
{% endif %}
{% endblock content-loop %}

my_zinnia_bootstrap/templates/zinnia/googled9943244a1802ac7.html
google-site-verification: googled9943244a1802ac7.html

my_zinnia_bootstrap/templates/zinnia/sitemap.html
{% extends "zinnia:zinnia/sitemap.html" %}
{% load i18n zinnia mptt_tags %}

{% block content %}
<h1>{% trans "Sitemap" %}</h1>

<div class="entriesbycategories">
  <h2>{% trans "Entries per categories" %}</h2>
  {% for category in categories %}
  <h3>{{ category }}</h3>
  <ul class="list-group">
    {% for entry in category.entries_published.all %}
    <li class="list-group-item">
      <a href="{{ entry.get_absolute_url }}" title="{{ entry.title }}" rel="bookmark">{{ entry.title }}</a>
      {% with comment_count=entry.comments.count %}
      <span class="badge">
        {{ comment_count }} {% trans "comment" %}{{ comment_count|pluralize }}
      </span>
      {% endwith %}
    </li>
    {% empty %}
    <li class="list-group-item">
      {% trans "No entries yet." %}
    </li>
    {% endfor %}
  </ul>
  {% endfor %}
</div>

<div class="montharchives">
  <h2>{% trans "Monthly archives" %}</h2>
  {% get_archives_entries %}
</div>
{% endblock content %}

my_zinnia_bootstrap/templates/zinnia/skeleton.html
{% extends "my_zinnia_bootstrap:zinnia/navigation.html" %}
{% load i18n staticfiles %}
{% block my_content %}
<!--    {% block slider %}{% endblock %}-->
    {% block zinnia_content %}
    <div class="container">
      <div class="row">
        <div id="content" class="hfeed col-xs-12 col-sm-8 col-md-8 col-lg-8">
          {% block breadcrumbs %}{% endblock %}
          {% block content %}
          <div class="links">
            <h3>{% trans "Useful links" %}</h3>
            <ul>
              <li>
                <a href="{% url 'zinnia:entry_archive_index' %}" title="{% trans "Weblog index" %}">
                  {% trans "Weblog index" %}
                </a>
              </li>
              <li>
                <a href="{% url 'zinnia:sitemap' %}" title="{% trans "Sitemap" %}">
                  {% trans "Sitemap" %}
                </a>
              </li>
            </ul>
          </div>
          <div class="search">
            <h3>{% trans "Search" %}</h3>
            {% include "zinnia/tags/search_form.html" %}
          </div>
          {% endblock content %}
        </div>
        <div id="sidebar" class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          {% block sidebar %}
	  {% endblock sidebar %}
       <!-- </div>-->
      </div>
    </div>
    {% endblock zinnia_content %}
{% endblock my_content %}
{% block footer_content %}      
<p>{% blocktrans %}Powered by <a href="http://www.djangoproject.com">Django</a> and <a href="https://github.com/Fantomas42/django-blog-zinnia">Zinnia {{ ZINNIA_VERSION }}</a>.{% endblocktrans %}</p>
{% endblock footer_content %}

my_zinnia_bootstrap/templates/zinnia/skeleton_old.html
{% load i18n staticfiles %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <title>Marks' Weblog - {% block title %}{% endblock title %}{% block title-page %}{% endblock title-page %}</title>
    <meta name="robots" content="follow, all" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="{% block meta-description %}{% trans "Just another Zinnia weblog." %}{% endblock meta-description %}{% block meta-description-page %}{% endblock meta-description-page %}" />
    <meta name="keywords" content="{% block meta-keywords %}django, blog, weblog, zinnia{% endblock meta-keywords %}" />
    <meta name="author" content="markymo5115" />
    {% block meta %}{% endblock meta %}
    <link rel="pingback" href="/xmlrpc/" />
    <link rel="home" href="{% url 'zinnia:entry_archive_index' %}" />
    <link rel="stylesheet" href="{% static "zinnia_bootstrap/bootstrap/css/bootstrap.min.css" %}" />
    <style type="text/css">
      body {
        padding-top: 230px;
	background: white;
      }

      .navbar{
	border-radius: 0;
	}

      .navbar-header{
	background: url('{% static "zinnia_bootstrap/img/header.png" %}');
	background-position: right;
	background-repeat: no-repeat;
	background-colour: transparent;
	width: 100%;
	}

      .navbar-brand{
	background: url('{% static "zinnia_bootstrap/img/logo.png" %}');
	height: 165px;
	width: 207px;
	}
      body > nav img {
        margin-top: 5px;
        margin-left: 10px;
      }
      p.entry-discussions {
        margin-bottom: 0px;
      }
 
     div.row img.thumbnail {
	margin-bottom: 5px;
	display: inline-block;
	}
    </style>
    <!--[if lt IE 9]>
        <script src="{% static "zinnia_bootstrap/assets/js/html5shiv.js" %}"></script>
        <script src="{% static "zinnia_bootstrap/assets/js/respond.min.js" %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static "zinnia_bootstrap/img/favicon.ico" %}" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "zinnia_bootstrap/assets/ico/apple-touch-icon-144-precomposed.png" %}" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "zinnia_bootstrap/assets/ico/apple-touch-icon-114-precomposed.png" %}" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "zinnia_bootstrap/assets/ico/apple-touch-icon-72-precomposed.png" %}" />
    <link rel="apple-touch-icon-precomposed" href="{% static "zinnia_bootstrap/assets/ico/apple-touch-icon-57-precomposed.png" %}" />
    {% block link %}{% endblock link %}
    {% block script %}{% endblock script %}
  </head>
  <body class="zinnia {% block body-class %}{% endblock body-class %}">
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
<!--          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">{% trans "Toggle navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="{% static "zinnia_bootstrap/img/logo.png" %}" class="pull-left" alt="Mark's Weblog" />--->

          <a href="{% url 'zinnia:entry_archive_index' %}" title="Marks' Weblog" class="navbar-brand" rel="home">
            Marks' Weblog
          </a>
        </div>	
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">{% trans "Toggle navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-left">
            {% url 'zinnia:category_list' as category_list_url %}
            <li {% if category_list_url in request.path %}class="active"{% endif %}>
              <a href="{{ category_list_url }}" title="{% trans "Category list" %}">
                {% trans "Categories" %}
              </a>
            </li>
            {% url 'zinnia:author_list' as author_list_url %}
            <li {% if author_list_url in request.path %}class="active"{% endif %}>
              <a href="{{ author_list_url }}" title="{% trans "Author list" %}">
                {% trans "Authors" %}
              </a>
            </li>
            {% url 'zinnia:tag_list' as tag_list_url %}
            <li {% if tag_list_url in request.path %}class="active"{% endif %}>
              <a href="{{ tag_list_url }}" title="{% trans "Tag list" %}">
                {% trans "Tags" %}
              </a>
            </li>
            <li class="divider-vertical"></li>
          </ul>
          <form method="get" action="{% url 'zinnia:entry_search' %}" class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="search-query form-control" placeholder="{% trans 'Search' %}" name="pattern" value="{{ pattern }}" />
            </div>
            <button type="submit" name="submit" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            {% url 'zinnia:sitemap' as sitemap_url %}
            <li {% if sitemap in request.path %}class="active"{% endif %}>
            <li>
              <a href="{{ sitemap_url }}" title="{% trans "Sitemap" %}" class="sitemap">
                {% trans "Sitemap" %}
              </a>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <a href="{% url 'zinnia:entry_feed' %}" title="{% trans "RSS Feed of latest entries" %}" class="feeds">
                {% trans "RSS Feed" %}
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<!--    {% block slider %}{% endblock %}-->
    {% block zinnia_content %}
    <div class="container">
      <div class="row">
        <div id="content" class="hfeed col-xs-12 col-sm-8 col-md-8 col-lg-8">
          {% block breadcrumbs %}{% endblock %}
          {% block content %}
          <div class="links">
            <h3>{% trans "Useful links" %}</h3>
            <ul>
              <li>
                <a href="{% url 'zinnia:entry_archive_index' %}" title="{% trans "Weblog index" %}">
                  {% trans "Weblog index" %}
                </a>
              </li>
              <li>
                <a href="{% url 'zinnia:sitemap' %}" title="{% trans "Sitemap" %}">
                  {% trans "Sitemap" %}
                </a>
              </li>
            </ul>
          </div>
          <div class="search">
            <h3>{% trans "Search" %}</h3>
            {% include "zinnia/tags/search_form.html" %}
          </div>
          {% endblock content %}
        </div>
        <div id="sidebar" class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          {% block sidebar %}
	  {% endblock sidebar %}
       <!-- </div>-->
      </div>
    </div>
    {% endblock zinnia_content %}
    <footer class="container">
      <p>{% blocktrans %}Powered by <a href="http://www.djangoproject.com">Django</a> and <a href="https://github.com/Fantomas42/django-blog-zinnia">Zinnia {{ ZINNIA_VERSION }}</a>.{% endblocktrans %}</p>
    </footer>
    <script type="text/javascript" src="{% static "zinnia_bootstrap/assets/js/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "zinnia_bootstrap/bootstrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>